In [ ]:
print("안녕, 콜라보레이토리")

안녕, 콜라보레이토리


In [ ]:
import tensorflow as tf

In [ ]:
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [ ]:
import pandas as pd

In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
lemonade = pd.read_csv(파일경로)
 
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(파일경로)
 
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(파일경로)

In [ ]:
# 데이터 모양으로 확인하기
print(lemonade.shape)
print(boston.shape)
print(iris.shape)

(6, 2)
(506, 14)
(150, 5)


In [ ]:
# 칼럼이름 출력
print(lemonade.columns)
print(boston.columns)
print(iris.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [ ]:
print(lemonade[['온도']].shape, lemonade[['판매량']].shape)
print(boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']].shape, boston[['medv']].shape)
print(iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']].shape, iris[['품종']].shape)

(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)


In [ ]:
lemonade.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [ ]:
boston.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
독립 = lemonade[['온도']]
종속 = lemonade[['판매량']]

In [ ]:
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 3ms/step - loss: 371.9771
Epoch 2/1000
1/1 [==============================] - 0s 5ms/step - loss: 371.0785
Epoch 3/1000
1/1 [==============================] - 0s 4ms/step - loss: 370.1811
Epoch 4/1000
1/1 [==============================] - 0s 4ms/step - loss: 369.2848
Epoch 5/1000
1/1 [==============================] - 0s 4ms/step - loss: 368.3897
Epoch 6/1000
1/1 [==============================] - 0s 4ms/step - loss: 367.4957
Epoch 7/1000
1/1 [==============================] - 0s 4ms/step - loss: 366.6028
Epoch 8/1000
1/1 [==============================] - 0s 4ms/step - loss: 365.7109
Epoch 9/1000
1/1 [==============================] - 0s 4ms/step - loss: 364.8201
Epoch 10/1000
1/1 [==============================] - 0s 4ms/step - loss: 363.9304
Epoch 11/1000
1/1 [==============================] - 0s 4ms/step - loss: 363.0419
Epoch 12/1000
1/1 [==============================] - 0s 4ms/step - loss: 362.1543
Epoch 13/1000
1/1 [======

In [ ]:
print(model.predict([[15]]))

[[30.630793]]


In [ ]:
import tensorflow as tf
import pandas as pd

In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
데이터 = pd.read_csv(파일경로)
데이터.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [ ]:
독립 = 데이터[['온도']]
종속 = 데이터[['판매량']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [ ]:
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
model.fit(독립, 종속, epochs=10000, verbose=0)

In [ ]:
model.predict(독립)

array([[39.990055],
       [41.989346],
       [43.988636],
       [45.987926],
       [47.987213],
       [49.986504]], dtype=float32)

In [ ]:
model.predict([[15]])

array([[29.99361]], dtype=float32)

In [ ]:
import tensorflow as tf
import pandas as pd

In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [ ]:
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000
16/16 [==============================] - 0s 993us/step - loss: 26.7515
Epoch 2/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.3065
Epoch 3/1000
16/16 [==============================] - 0s 932us/step - loss: 26.8349
Epoch 4/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.5943
Epoch 5/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.8241
Epoch 6/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.2742
Epoch 7/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.9642
Epoch 8/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.5257
Epoch 9/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.6762
Epoch 10/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.5252
Epoch 11/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.8382
Epoch 12/1000
16/16 [==============================] - 0s 1ms/step - loss: 26.4762
Epoch 13/

In [ ]:
print(model.predict(독립[:5]))

[[29.855286]
 [24.690905]
 [31.056765]
 [30.007137]
 [29.543703]]


In [ ]:
종속[:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [ ]:
# 모델의 수식 확인
model.get_weights()

[array([[-0.08880123],
        [ 0.05568008],
        [-0.04660102],
        [ 2.967079  ],
        [ 1.8270448 ],
        [ 4.961768  ],
        [-0.00545132],
        [-0.98852193],
        [ 0.17488849],
        [-0.00999293],
        [-0.30225828],
        [ 0.01451114],
        [-0.4964967 ]], dtype=float32), array([3.8738143], dtype=float32)]

In [ ]:
import pandas as pd
import tensorflow as tf

In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(파일경로)
# 원핫인코딩
iris = pd.get_dummies(iris)
iris

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]

In [ ]:
iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [ ]:
독립 = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)   # sigmoid, softmax(확률!) 차이점!!(분류) <-> Identity(회귀)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')    # categorical_crossentropy(분류) <-> mse(회귀)

In [ ]:
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 3ms/step - loss: 0.4680 - accuracy: 0.9267
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4652 - accuracy: 0.9067
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4641 - accuracy: 0.9200
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4627 - accuracy: 0.9133
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4610 - accuracy: 0.9133
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4598 - accuracy: 0.8867
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4590 - accuracy: 0.9267
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4566 - accuracy: 0.9200
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4558 - accuracy: 0.9333
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4546 - accuracy: 0.9200
Epoch 11/100
5/5 [===========

In [ ]:
model.predict(독립[-5:])

array([[0.00219471, 0.33455074, 0.6632546 ],
       [0.00427799, 0.37182763, 0.6238944 ],
       [0.0049002 , 0.3701445 , 0.62495536],
       [0.00222406, 0.24136065, 0.7564153 ],
       [0.0077505 , 0.32806912, 0.66418034]], dtype=float32)

In [ ]:
종속[-5:]

품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1

In [ ]:
model.get_weights()

[array([[ 0.35867903,  0.4654598 , -0.30496114],
        [ 0.56143075, -0.4607384 , -0.6336019 ],
        [-1.4716921 , -0.8593108 , -0.14999929],
        [-1.9777263 ,  0.29149264,  1.3403864 ]], dtype=float32),
 array([ 0.7125739 , -0.31319663, -0.04929054], dtype=float32)]

In [ ]:
import tensorflow as tf
import pandas as pd

In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(파일경로)
boston

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0    0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
501  0.06263   0.0  11.93     0  0.573  ...  273     21.0  391.99   9.67  22.4
502  0.04527   0.0  11.93     0  0.573  ...  273     21.0  396.90   9.08  20.6
503  0.06076   0.0  11.93     0  0.573  ...  273     21.0  396.90   5.64  23.9
504  0.10959   0.0  11.93     0  0.573  ...  273     21.0  393.45   6.48  22.0
505  0.04741   0.0  11.93     0  0.573  ...  273     21.0  396.90   7.88  11.9

[506 rows x 14 columns]

In [ ]:
독립 = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = boston[['medv']]

In [ ]:
X = tf.keras.layers.Input([13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000
16/16 [==============================] - 0s 1ms/step - loss: 41.3153
Epoch 2/1000
16/16 [==============================] - 0s 1ms/step - loss: 40.9266
Epoch 3/1000
16/16 [==============================] - 0s 1ms/step - loss: 43.7726
Epoch 4/1000
16/16 [==============================] - 0s 1ms/step - loss: 41.5956
Epoch 5/1000
16/16 [==============================] - 0s 1ms/step - loss: 43.2048
Epoch 6/1000
16/16 [==============================] - 0s 1ms/step - loss: 41.3457
Epoch 7/1000
16/16 [==============================] - 0s 1ms/step - loss: 40.8186
Epoch 8/1000
16/16 [==============================] - 0s 1ms/step - loss: 45.4964
Epoch 9/1000
16/16 [==============================] - 0s 990us/step - loss: 43.4987
Epoch 10/1000
16/16 [==============================] - 0s 1ms/step - loss: 40.0224
Epoch 11/1000
16/16 [==============================] - 0s 1ms/step - loss: 42.2157
Epoch 12/1000
16/16 [==============================] - 0s 1ms/step - loss: 45.5804
Epoch 13/10

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(독립[:5]))
print(종속[:5])

[[34.01083 ]
 [23.960896]
 [33.812042]
 [35.120777]
 [30.789627]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(파일경로)
iris = pd.get_dummies(iris)
iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [ ]:
독립 = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

In [ ]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_6 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_7 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(독립, 종속, epochs=100)

In [ ]:
model.predict(독립[:5])

array([[9.9973601e-01, 1.2488324e-04, 1.3908102e-04],
       [9.9955207e-01, 2.3907906e-04, 2.0890904e-04],
       [9.9962866e-01, 1.9056760e-04, 1.8081421e-04],
       [9.9913031e-01, 4.9288874e-04, 3.7682336e-04],
       [9.9970943e-01, 1.3710745e-04, 1.5354340e-04]], dtype=float32)

In [ ]:
종속[:5]

품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0

In [ ]:
import pandas as pd
iris = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv')
# 원핫인코딩    df = pd.get_dummies(df)은 숫자 데이터이므로 실행 X
# =>> 품종 타입을 범주형으로 바꾸어 준다.
iris['품종'] = iris['품종'].astype('category')
iris = pd.get_dummies(iris)
iris

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
0     5.1  3.5    1.4   0.2     1     0     0
1     4.9  3.0    1.4   0.2     1     0     0
2     4.7  3.2    1.3   0.2     1     0     0
3     4.6  3.1    1.5   0.2     1     0     0
4     5.0  3.6    1.4   0.2     1     0     0
..    ...  ...    ...   ...   ...   ...   ...
145   6.7  3.0    5.2   2.3     0     0     1
146   6.3  2.5    5.0   1.9     0     0     1
147   6.5  3.0    5.2   2.0     0     0     1
148   6.2  3.4    5.4   2.3     0     0     1
149   5.9  NaN    5.1   1.8     0     0     1

[150 rows x 7 columns]

In [ ]:
iris.isna().sum()

꽃잎길이     0
꽃잎폭      1
꽃받침길이    0
꽃받침폭     0
품종_0     0
품종_1     0
품종_2     0
dtype: int64

In [ ]:
iris = iris.fillna(iris['꽃잎폭'].mean())

In [ ]:
iris

꽃잎길이       꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
0     5.1  3.500000    1.4   0.2     1     0     0
1     4.9  3.000000    1.4   0.2     1     0     0
2     4.7  3.200000    1.3   0.2     1     0     0
3     4.6  3.100000    1.5   0.2     1     0     0
4     5.0  3.600000    1.4   0.2     1     0     0
..    ...       ...    ...   ...   ...   ...   ...
145   6.7  3.000000    5.2   2.3     0     0     1
146   6.3  2.500000    5.0   1.9     0     0     1
147   6.5  3.000000    5.2   2.0     0     0     1
148   6.2  3.400000    5.4   2.3     0     0     1
149   5.9  3.054362    5.1   1.8     0     0     1

[150 rows x 7 columns]

In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(파일경로)
boston.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [ ]:
독립 = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = boston[['medv']]

In [ ]:
X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000
16/16 [==============================] - 0s 2ms/step - loss: 14.7750
Epoch 2/1000
16/16 [==============================] - 0s 2ms/step - loss: 16.5511
Epoch 3/1000
16/16 [==============================] - 0s 2ms/step - loss: 17.9792
Epoch 4/1000
16/16 [==============================] - 0s 1ms/step - loss: 17.1827
Epoch 5/1000
16/16 [==============================] - 0s 1ms/step - loss: 18.3664
Epoch 6/1000
16/16 [==============================] - 0s 2ms/step - loss: 16.2524
Epoch 7/1000
16/16 [==============================] - 0s 2ms/step - loss: 18.3411
Epoch 8/1000
16/16 [==============================] - 0s 2ms/step - loss: 15.8443
Epoch 9/1000
16/16 [==============================] - 0s 2ms/step - loss: 15.2336
Epoch 10/1000
16/16 [==============================] - 0s 2ms/step - loss: 15.6070
Epoch 11/1000
16/16 [==============================] - 0s 2ms/step - loss: 17.0253
Epoch 12/1000
16/16 [==============================] - 0s 2ms/step - loss: 15.6426
Epoch 13/1000